In [138]:
%matplotlib inline
from scipy.io import loadmat,savemat
from scipy.linalg import *
from numpy import *
from os import listdir
#from sklearn.externals import joblib as pickle
import pickle

### <font color="red">Objective: Maximize the stiffness coefficient C11</font>

### <font color="orange"> Design Constraint: C12 stiffness coefficient should be greater than 75 GPa.</font>

## <font color="blue"> Optimization problem formulation:</font>

#### <font color="green">max C11</font>
<font color="green"subject to :</font>
<font color="purple">  C12>75 GPa</font>


In [2]:
def loadData(name,path):
    '''
    This loads a pickle file and returns the content which is a DICTIONARY object in our case.
    '''
    if ".pkl" in name:
            name = name.split(".pkl")[0]
    if "/" in name:
            name = name.split("/",1)[1]

    with open(path+"/"+name + '.pkl', 'rb') as f:
          return pickle.load(f)

def saveData(obj, name,path):
    '''
    This saves a object into a pickle file. In our case, it is generally a DICTIONARY object.
    '''

    with open(path+"/"+name + '.pkl', 'wb') as f:
            pickle.dump(obj, f)#, pickle.HIGHEST_PROTOCOL)

### <font color="red">Optimum polycrystal solution C11 =  167.7773  GPa</font>
#### with 
##### <font color="blue">C12 = 75.2360 GPa</font>

### <font color="green">Optimum single crystal solution</font>

##### αx = 7.144e-6 (1/K)
##### C11 = 164.9332 GPa
##### C12 = 75.0058 GPa

In [11]:
titaniumData = loadmat('alphatitaniumsmall.mat')

### <font color="blue"> Extracting the data files </font>

In [12]:
volumefraction = titaniumData['volumefraction'][0]
thermalexpansion = titaniumData['thermalexpansion']
stiffness = titaniumData['stiffness']

In [5]:
def results(odf):
    
    C11 = odf[50]
    C12 = odf[51]
    opt = odf[52]
    return 'C11=',C11,'C12=',C12,'opt=',opt

In [7]:
C11 = odf[50]
C12 = odf[51]
opt = odf[52]
print 'C11=',C11,'C12=',C12,'opt=',opt

C11= 156.856680219 C12= 79.6111939505 opt= 10000.0


In [50]:
data = loadmat('data1_first5Generator_2000.mat')

In [52]:
for odf in data['odfs']:
    print getSum(odf[:50])

1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0


In [12]:
titaniumDat = loadmat('alphatitaniumsmall.mat')
titaniumDat['thermalexpansion'][0]

array([  2.85543098e-07,   7.38964043e-07,   2.06758806e-07,
         2.28572458e-07,   2.28572458e-07,   2.06758806e-07,
         1.82582886e-07,   1.82582886e-07,   2.26210191e-07,
         2.26210191e-07,   1.80220619e-07,   1.80220619e-07,
         2.02034271e-07,   2.02034271e-07,   1.14082861e-07,
         1.14082861e-07,   9.94945119e-08,   9.94945119e-08,
         1.23524102e-07,   1.23524102e-07,   9.43474030e-08,
         9.43474030e-08,   1.18376993e-07,   1.18376993e-07,
         1.03788644e-07,   1.03788644e-07,   8.36864040e-08,
         6.61339175e-08,   9.24626472e-08,   5.73576743e-08,
         8.36864040e-08,   6.61339175e-08,   7.84867566e-08,
         9.33234456e-08,   7.84867566e-08,   9.33234456e-08,
         6.36462118e-08,   6.36462118e-08,   9.33195898e-08,
         9.33195898e-08,   6.36423560e-08,   6.36423560e-08,
         7.84790450e-08,   7.84790450e-08,   1.01741053e-07,
         8.06872806e-08,   1.12267939e-07,   7.01603945e-08,
         1.01741053e-07,

In [17]:
constraint = titaniumDat['volumefraction'][0]
constraint

array([ 0.03153236,  0.08391342,  0.02473832,  0.02473832,  0.02473832,
        0.02473832,  0.02473832,  0.02473832,  0.02473832,  0.02473832,
        0.02473832,  0.02473832,  0.02473832,  0.02473832,  0.01320576,
        0.01320576,  0.01320576,  0.01320576,  0.01320576,  0.01320576,
        0.01320576,  0.01320576,  0.01320576,  0.01320576,  0.01320576,
        0.01320576,  0.00985683,  0.00985683,  0.00985683,  0.00985683,
        0.00985683,  0.00985683,  0.01016979,  0.01016979,  0.01016979,
        0.01016979,  0.01016979,  0.01016979,  0.01016979,  0.01016979,
        0.01016979,  0.01016979,  0.01016979,  0.01016979,  0.01197505,
        0.01197505,  0.01197505,  0.01197505,  0.01197505,  0.01197505])

In [186]:
data = []

Filename = []
for File in listdir('Data'):

    Filename += [File]
    data += [loadmat('Data/'+File)]



In [187]:
opt = []
opts = []
odfs = []
maxOdf = [0]*50
maxOdfI = [[0]*50]*len(data)#, maxOdf]#, maxOdf]#, maxOdf]
maxOpt = 0
maxOptI = [0]*len(data)#4
count = 0
total = 0
wrong = [[]]*len(data)
countwrong = [0]*len(data)
for i in range(len(data)):
    for odf in data[i]['odfs']:
        opt += [odf[50]]
        odfs += [odf[:50]]
        total += 1
        if checkSum(odf[:50]):
            count += 1
        else:
            wrong[i] += [odf[:50]]
#             countwrong[i] += 1
        if odf[50]>maxOpt:
            maxOptI[i] = odf[50]
            maxOdfI[i] = odf[:50]




In [188]:
for i in range(len(data)):
    print i,Filename[i],maxOptI[i],getC12(maxOdfI[i])

0 C11_first4Generator_100000.mat 160.929742103 75.0047001813
1 C11_first6Generator_20000.mat 159.121480109 75.5620115699
2 C11_SmallPartition2_300000.mat 165.339382545 75.0454599649
3 C11_SmallPartition3_300000.mat 159.571185539 76.9185158886
4 C11_SmallPartition4_300000.mat 159.429380086 77.039245703
5 C11_SmallPartition5_100000.mat 156.763634568 75.2168620574
6 C11_SmallPartition5_300000.mat 159.592938815 75.5974784823
7 C11_SmallPartition6_100000.mat 160.191147529 75.4785294383
8 C11_SmallPartition7_100000.mat 157.199073186 77.1953144912
9 data_SmallPartition2_1000.mat 155.667076773 76.209123008


In [189]:
total,count

(138487, 138487)

In [172]:
getSum(maxOdfI[4])

1.0

In [173]:
maxOdfI[4]

array([  4.97128194,   0.6408896 ,   0.        ,   1.40677917,
         0.        ,   1.07988966,   1.4821351 ,   0.        ,
         0.        ,   4.07633161,   0.        ,   0.        ,
         0.        ,   0.94861838,   0.        ,   0.        ,
         0.        ,   0.        ,  11.68759484,   0.        ,
         0.        ,   0.        ,   3.56989487,   7.56411631,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   6.11562875,
         0.        ,   0.        ,   0.        ,   0.        ,
         4.42492838,   5.55682217,   0.        ,   0.        ,
         0.        ,  10.1806    ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.02254541,   0.        ])

In [170]:
maxVal = {'odf':maxOdfI[4]}
savemat('morethanLP.mat',maxVal)

In [120]:
for odf in wrong[0][:10]:
    print getSum(odf)

1.03263293248
1.04115590815
1.01879753351
1.04612337986
1.00791291571
1.01766999225
1.0262664485
1.03203885708
1.02451084223
1.04653812524


In [129]:
total,count

(1024, 1024)

In [30]:
count = 0
validOdf = []
for odf in data[0]['odfs']:
    if checkSum(odf)==True:
        count += 1
        validOdf += [odf]

In [180]:
def getC12(odf):

    C = stiffness.dot(odf).reshape(6,6);  # averaged stiffness matrix
    C12 = C[0][1]
    return C12
#     alpha = thermalexpansion.dot(odf).reshape(3,3); # thermal expansion tensor
#     alphaxx = alpha[0][0];
#     print alphaxx

# def getC2():
    
# def getExpansion():
    
    

In [111]:
x = [[]]*3
x

[[], [], []]

In [12]:
maximumOdf = {'odf':maxOdf}
savemat('maximumOdf',maximumOdf)

In [26]:
x = loadmat('maximumOdf.mat')
x['odf']

array([[  0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  25.2821043 ,   6.81563517,
          0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ,
         65.02285068,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ]])

In [48]:
y = loadmat('alphatitaniumsmall.mat')
y.keys('v')

['volumefraction',
 'thermalexpansion',
 '__header__',
 '__globals__',
 'stiffness',
 '__version__']

In [33]:
Sum = 0
newOdf = [0]*50
for i in range(50):
    a = volumefraction[i]*maxOdf[i]
    if Sum+a>1:
        newOdf[i]=(1-Sum)/volumefraction[i]
        break
    else:
        newOdf[i] = maxOdf[i]
    Sum = Sum + a


In [15]:
def getSum(odf):
    Sum = 0
    for i in range(50):
        Sum += volumefraction[i]*odf[i]
    return Sum

In [26]:
def checkSum(odf):
    Sum = FiveSig(getSum(odf))
    if Sum !=1.0:
        return False
    else:
        return True
#     return Sum

In [35]:
for i in range(4):
    print getSum(maxOdfI[i])

1.00737149974
1.02332485318
1.01006479154
1.03523175208


In [18]:
stiffness_avg = stiffness.dot(odf)
stiffness_avg.reshape(6,6)


array([[ 183.56311018,   82.9671108 ,   88.58359421,    2.79862418,
           1.13720681,   -0.90823487],
       [  82.9671108 ,  190.54247559,   84.16617111,   -2.51820258,
          -1.49969147,   -0.57366663],
       [  88.58359421,   84.16617111,  181.52176458,   -2.06949264,
           1.24595028,    0.88562018],
       [   2.79862418,   -2.51820258,   -2.06949264,   50.352582  ,
          -0.93216944,    1.19359208],
       [   1.13720681,   -1.49969147,    1.24595028,   -0.93216944,
          46.95981205,   -2.65543704],
       [  -0.90823487,   -0.57366663,    0.88562018,    1.19359208,
          -2.65543704,   51.7212652 ]])

In [25]:
getC11C12([  0.00000000e+00,   4.04139735e+01,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          1.71282918e-02,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00])

531.971421333 269.995687525
2.98660717028e-05


In [18]:
maxodf = {'odf':maxOdf}
savemat('maxOdfTitanium',maxodf)

In [46]:
data = {'odfs':odfs,'opt':opt}
saveData(data,'titaniumData2','Data')

In [35]:
name='titaniumData'
path = 'Data'
obj = data

In [38]:
 with open(path+"/"+name + '.pkl', 'wb') as f:
        pickle.dump(obj, f)#, pickle.HIGHEST_PROTOCOL)

In [100]:
[[1,0]]*2

[[1, 0], [1, 0]]

In [3]:
y = loadmat('odf_LP.mat')
y.keys()


['__version__', '__header__', 'odf', '__globals__']

In [6]:
odf = []
for item in y['odf']:
    odf += [item[0]]

In [17]:
getSum(odf)

0.99999999999999989

In [20]:
def FiveSig(x):
    return float("{0:.5f}".format(x))

In [25]:
FiveSig(0.999989)

0.99999