In [2]:
load linprog849_compliance_node
compliance = propmat(1:36,:);

load linprog_yield_node
yield = propmat;

In [3]:
odf = load('yield_first5Generator_50.mat')


odf = 

  struct with fields:

    randsize: 50
        odfs: [40�389 double]
        Data: [40�391 double]
     t_Y_REk: 3.1870



In [4]:
ODF = odf.odfs(1,1:388);

In [36]:
size(yield), size(compliance), size(ODF')


ans =

     1   388


ans =

    36   388


ans =

   388     1



In [35]:
yield*ODF'


ans =

  205.7612



In [5]:
S = compliance*ODF';

In [6]:
S11 = S(1,:) 


S11 =

    0.1436



In [8]:
S22 = S(8,:) 


S22 =

    0.1236



In [9]:
length(S)


ans =

    36



In [10]:
Smatrix = reshape(S,6,6);

In [2]:
x = load('linprog_yield_node');

In [3]:
x.volume

Error using eval
Undefined function or variable 'volumefraction'.



In [8]:
odfDim = 388;

In [3]:
dsize = 100;
fsize = 3;

In [4]:
cutsize = fsize - 1;
randSep = sort(rand(1,cutsize));



In [5]:
randIntvl = diff([0,randSep,1]);

In [9]:
randInd = randperm(odfDim,fsize);

In [4]:
load populationYield_nonLinear;
population


population =

  Columns 1 through 13

   385   372   315   246   374    42   313   317   196   334   337   369   371

  Columns 14 through 26

   384     3   257   264   266   139   142   272   147   153   324    27   157

  Columns 27 through 39

    32   161   163    38   295   305   310   314   194   182   225   177   332

  Columns 40 through 52

   339   340   214   343    91   350   351   224   367   108   365   381   368

  Columns 53 through 54

   125   255



In [6]:
data = load('alphatitaniummedium.mat');

In [ ]:
data


data = 

  struct with fields:

      volumefraction: [1�388 double]
           stiffness: [36�388 double]
    thermalexpansion: [9�388 double]



In [9]:
a = "hello";
b = a+"hi";
b


b = 

    "hellohi"

