In [1]:
sat = 0; 
count = 0;
propFunc = @main_alpha_Ti;
odfs = [];
Data = [];
notSat = [];

data_RandEvery5 = [];
odfDim = 50;

### constraint is volume fraction for the microstructure

In [2]:
constraint = [ 0.03153236,  0.08391342,  0.02473832,  0.02473832,  0.02473832,
        0.02473832,  0.02473832,  0.02473832,  0.02473832,  0.02473832,
        0.02473832,  0.02473832,  0.02473832,  0.02473832,  0.01320576,
        0.01320576,  0.01320576,  0.01320576,  0.01320576,  0.01320576,
        0.01320576,  0.01320576,  0.01320576,  0.01320576,  0.01320576,
        0.01320576,  0.00985683,  0.00985683,  0.00985683,  0.00985683,
        0.00985683,  0.00985683,  0.01016979,  0.01016979,  0.01016979,
        0.01016979,  0.01016979,  0.01016979,  0.01016979,  0.01016979,
        0.01016979,  0.01016979,  0.01016979,  0.01016979,  0.01197505,
        0.01197505,  0.01197505,  0.01197505,  0.01197505,  0.01197505];

In [3]:
constraint 

In [4]:
for i = 1:randsize

  remainFac = 1:1:odfDim-1;
  setFac = zeros(1,odfDim-1);
  thsd = 1;

  outerLp = 1;
  while isempty(remainFac) == 0

        if length(remainFac) < 5
            r = 1;
        else
            r = 5;
        end

        randDraw = randsample(length(remainFac),r);
        randFac = remainFac(randDraw);
        remainFac(randDraw) = [];

        randFacRand = rand(1,r).*thsd;

        innerLp(outerLp) = 1;
        while sum(randFacRand) > thsd
            randFacRand = rand(1,r).*thsd;
            innerLp(outerLp) = innerLp(outerLp) + 1;
        end

        thVector(outerLp) = thsd;

        thsd = thsd - sum(randFacRand);

        setFac(randFac) = randFacRand./constraint(randFac);

        outerLp = outerLp + 1;
    end

      odf = [setFac,thsd/constraint(end)];
      if (odf>=0) == true(1,length(odf))
          [val,C11,C12] = propFunc(odf);
          println(C11);
          println(C12)
          if val == -10000;
              count = count + 1;
              notSat = [notSat;odf];
            else
    	        sat = sat + 1;
    	         disp(strcat('row',num2str(sat),'satisfied....'));
               println(C11,'      ',C12,'       ',val);
    	          odfs = [odfs;odf,-val];
                Data = [Data;odf,C11,C12,-val];
            end


        end

  end

Inner matrix dimensions must agree.


In [8]:
odf'

ans =

    0.0044
    0.1834
    0.0000
    0.0000
    8.0115
    0.0014
   11.1291
    0.0051
    0.0000
    0.0000
    0.0000
    0.0008
    0.1707
    0.0000
    0.0026
    0.0000
    0.0000
    0.0000
    1.8156
    0.0000
    0.0000
    0.8112
    0.0000
    0.0000
    0.0302
    0.1196
    0.0019
    0.0005
    0.0832
    1.0037
    2.5706
    0.0021
    0.0000
    0.1737
    0.0000
    0.0000
    1.4069
    0.0000
    0.0000
   33.7852
    0.0000
    0.0000
    0.0077
    0.0043
   16.5592
    0.0014
    1.8486
    0.0000
    0.0000
    0.0000


In [8]:
odf1 = notSat(1,:);
odf2 = notSat(2,:);
odf4 = notSat(4,:);

In [51]:
[val,C11,C12] = propFunc(odf1)

10000

opt =

      -10000


val =

      -10000


C11 =

  156.8567


C12 =

   79.6112


In [53]:
[val,C11,C12] = alpha_Ti(odf2)

10000

opt =

      -10000


val =

      -10000


C11 =

  156.8567


C12 =

   79.6112


In [26]:
A = [1 2 3;4 5 6;7 8 9]
A(1)

A =

     1     2     3
     4     5     6
     7     8     9


ans =

     1


In [55]:
num=2;

In [1]:
SmallPartition(2,4)


10000

opt =

      -10000

10000

opt =

      -10000

10000

opt =

      -10000

10000

opt =

      -10000

Elapsed time is 0.171135 seconds.
0.17236


In [1]:
[odfarray,dataarray] = randSmallPartition(2,10,@alpha_Ti);

1.8907e-05
402.8709
183.4454

opt =

  -1.8907e-05

Row1 processed.........
1.2747e-05
244.3847
117.3339

opt =

  -1.2747e-05

Row2 processed.........
1.8582e-05
335.9156
157.8662

opt =

  -1.8582e-05

Row3 processed.........
2.6372e-05
555.516
258.2012

opt =

  -2.6372e-05

Row4 processed.........
1.6663e-05
317.8643
153.7787

opt =

  -1.6663e-05

Row5 processed.........
1.5959e-05
294.5791
139.556

opt =

  -1.5959e-05

Row6 processed.........
1.4931e-05
333.9644
150.7354

opt =

  -1.4931e-05

Row7 processed.........
1.6912e-05
360.7716
163.2531

opt =

  -1.6912e-05

Row8 processed.........
1.5065e-05
329.5048
150.0259

opt =

  -1.5065e-05

Row9 processed.........
2.357e-05
412.8122
201.6976

opt =

  -2.3570e-05

Row10 processed.........


In [6]:
load alphatitaniumsmall

In [4]:
odf1 = data.notSat(1,1:50);
odf2 = data.notSat(2,1:50);
odf3 = data.notSat(3,1:50);

In [15]:
C = reshape(stiffness*odf1',6,6);

In [8]:
C = reshape(stiffness*odf1',6,6);  % averaged stiffness matrix
C11 = C(1,1);
C12 = C(1,2);


In [21]:
length(odf1)

ans =

     2


In [20]:
thermalexpansion

thermalexpansion =

   1.0e-06 *

  Columns 1 through 7

    0.2855    0.7390    0.2068    0.2286    0.2286    0.2068    0.1826
   -0.0000   -0.0000    0.0266    0.0112    0.0112    0.0266    0.0153
    0.0000    0.0000    0.0223   -0.0066    0.0066   -0.0223    0.0319
   -0.0000   -0.0000    0.0266    0.0112    0.0112    0.0266    0.0153
    0.2855    0.7390    0.2020    0.1802    0.1802    0.2020    0.2262
   -0.0000    0.0000   -0.0253    0.0330   -0.0330    0.0253   -0.0108
    0.0000    0.0000    0.0223   -0.0066    0.0066   -0.0223    0.0319
   -0.0000    0.0000   -0.0253    0.0330   -0.0330    0.0253   -0.0108
    0.2034    0.5831    0.1988    0.1988    0.1988    0.1988    0.1988

  Columns 8 through 14

    0.1826    0.2262    0.2262    0.1802    0.1802    0.2020    0.2020
    0.0153   -0.0153   -0.0153   -0.0112   -0.0112   -0.0266   -0.0266
   -0.0319   -0.0108    0.0108   -0.0330    0.0330   -0.0253    0.0253
    0.0153   -0.0153   -0.0153   -0.0112   -0.0112   -0.0266   -0.

In [4]:
odf1 = maximum.odf

odf1 =

  Columns 1 through 7

         0   40.4140         0         0         0         0         0

  Columns 8 through 14

         0         0         0         0         0         0         0

  Columns 15 through 21

         0         0         0         0         0         0         0

  Columns 22 through 28

         0         0         0         0         0         0         0

  Columns 29 through 35

         0         0         0         0         0    0.0171         0

  Columns 36 through 42

         0         0         0         0         0         0         0

  Columns 43 through 49

         0         0         0         0         0         0         0

  Column 50

         0


In [9]:
alpha = reshape(thermalexpansion*odf1',3,3); % thermal expansion tensor
alphaxx = alpha(1,1);
opt = alphaxx;
if C11<161 ||C12<75
    opt = 10000;
end
println(opt)
println(C11)
println(C12)
opt = -opt

2.9866e-05
531.9714
269.9957

opt =

  -2.9866e-05


In [11]:
constraint = [ 0.03153236,  0.08391342,  0.02473832,  0.02473832,  0.02473832,
          0.02473832,  0.02473832,  0.02473832,  0.02473832,  0.02473832,
          0.02473832,  0.02473832,  0.02473832,  0.02473832,  0.01320576,
          0.01320576,  0.01320576,  0.01320576,  0.01320576,  0.01320576,
          0.01320576,  0.01320576,  0.01320576,  0.01320576,  0.01320576,
          0.01320576,  0.00985683,  0.00985683,  0.00985683,  0.00985683,
          0.00985683,  0.00985683,  0.01016979,  0.01016979,  0.01016979,
          0.01016979,  0.01016979,  0.01016979,  0.01016979,  0.01016979,
          0.01016979,  0.01016979,  0.01016979,  0.01016979,  0.01197505,
          0.01197505,  0.01197505,  0.01197505,  0.01197505,  0.01197505];
  odfDim = size(constraint,1)*size(constraint,2);
  remainFac = 1:1:odfDim-1;
  setFac = zeros(1,odfDim-1);
  thsd = 1;

  outerLp = 1;
while isempty(remainFac) == 0

      if length(remainFac) < 5
          r = 1;
      else
          r = 5;
      end

      randDraw = randsample(length(remainFac),r);
      randFac = remainFac(randDraw);
      remainFac(randDraw) = [];

      randFacRand = rand(1,r).*thsd;

      innerLp(outerLp) = 1;
      while sum(randFacRand) > thsd
          randFacRand = rand(1,r).*thsd;
          innerLp(outerLp) = innerLp(outerLp) + 1;
      end

      thVector(outerLp) = thsd;

      thsd = thsd - sum(randFacRand);

      setFac(randFac) = randFacRand./constraint(randFac);

      outerLp = outerLp + 1;
  end
  odf = [setFac,thsd/constraint(end)];

In [12]:
odf

odf =

  Columns 1 through 7

    2.4938   12.1432    0.0000    0.0001    0.0228    1.7584    0.6524

  Columns 8 through 14

    0.0003    0.0000    0.0000    0.0000    0.0000    0.8228    0.0002

  Columns 15 through 21

    0.3984    0.0000    0.0427    0.0002    0.1471    0.0000    0.0013

  Columns 22 through 28

    0.0000    0.0000    0.0000    0.0000    0.0000    0.0000    0.0000

  Columns 29 through 35

    0.0000    0.0000    0.0000    1.3989    0.0610    0.0000    0.0000

  Columns 36 through 42

    0.0000   17.3174    0.0457    0.0000    0.0000    0.0000    1.3493

  Columns 43 through 49

    0.0142    0.5263    0.6014    0.0000    0.0055   29.7185    0.0000

  Column 50

    0.0000


In [4]:
  constraint = [ 0.03153236,  0.08391342,  0.02473832,  0.02473832,  0.02473832,
          0.02473832,  0.02473832,  0.02473832,  0.02473832,  0.02473832,
          0.02473832,  0.02473832,  0.02473832,  0.02473832,  0.01320576,
          0.01320576,  0.01320576,  0.01320576,  0.01320576,  0.01320576,
          0.01320576,  0.01320576,  0.01320576,  0.01320576,  0.01320576,
          0.01320576,  0.00985683,  0.00985683,  0.00985683,  0.00985683,
          0.00985683,  0.00985683,  0.01016979,  0.01016979,  0.01016979,
          0.01016979,  0.01016979,  0.01016979,  0.01016979,  0.01016979,
          0.01016979,  0.01016979,  0.01016979,  0.01016979,  0.01197505,
          0.01197505,  0.01197505,  0.01197505,  0.01197505,  0.01197505]; 

In [9]:
size(constraint,1)*size(constraint,2)

ans =

    50


In [8]:
mat = load('Data/data_SmallPartition2_50000.mat');
mat.odfs(1,:)

ans =

  Columns 1 through 7

         0         0         0         0         0         0         0

  Columns 8 through 14

         0         0         0         0         0         0         0

  Columns 15 through 21

         0         0         0         0         0         0         0

  Columns 22 through 28

         0         0         0   35.4283         0         0         0

  Columns 29 through 35

         0         0         0         0         0         0         0

  Columns 36 through 42

         0         0         0         0         0         0         0

  Columns 43 through 49

         0         0         0   53.9872         0         0         0

  Columns 50 through 51

         0    0.0000


In [2]:
maximum = load('betterSol.mat');

In [3]:
maximum.odf

ans =

  Columns 1 through 7

   15.9390         0         0         0         0         0         0

  Columns 8 through 14

         0         0         0         0         0         0         0

  Columns 15 through 21

         0         0         0         0         0         0         0

  Columns 22 through 28

         0         0         0         0         0         0         0

  Columns 29 through 35

         0   50.4631         0         0         0         0         0

  Columns 36 through 42

         0         0         0         0         0         0         0

  Columns 43 through 49

         0         0         0         0         0         0         0

  Column 50

         0


In [1]:
load alphatitaniumsmall

In [16]:
x = load('alphatitaniumsmall.mat');
x.c11

Reference to non-existent field 'c11'.


In [83]:
x = load('morethanLP.mat');

In [90]:
LP = load('odf_LP.mat');

In [104]:
alpha = reshape(thermalexpansion*LP.odf,3,3)

alpha =

   1.0e-05 *

    0.8180    0.0005    0.0000
    0.0005    0.8334    0.0000
    0.0000    0.0000    0.8047


In [103]:
alpha(1,1)

ans =

   8.2740e-06


In [89]:
x.odf

ans =

  Columns 1 through 7

    4.9713    0.6409         0    1.4068         0    1.0799    1.4821

  Columns 8 through 14

         0         0    4.0763         0         0         0    0.9486

  Columns 15 through 21

         0         0         0         0   11.6876         0         0

  Columns 22 through 28

         0    3.5699    7.5641         0         0         0         0

  Columns 29 through 35

         0         0         0    6.1156         0         0         0

  Columns 36 through 42

         0    4.4249    5.5568         0         0         0   10.1806

  Columns 43 through 49

         0         0         0         0         0         0    0.0225

  Column 50

         0


In [5]:
C = reshape(stiffness*maximum.odf',6,6)

C =

  167.7794   75.0425   69.3790   -0.0000    0.0000   -0.0000
   75.0425  154.8312   77.6487   -0.0000   -0.0000   -0.0000
   69.3790   77.6487  163.9781   -0.0000    0.0000    0.0000
   -0.0000   -0.0000   -0.0000   40.6622   -0.0000    0.0000
   -0.0000   -0.0000    0.0000   -0.0000   46.6555   -0.0000
   -0.0000   -0.0000    0.0000    0.0000   -0.0000   41.6996


In [6]:
C(1,1),C(1,2)


ans =

  167.7794


ans =

   75.0425


In [88]:
sum(x.odf.*volumefraction)

ans =

     1


In [14]:
C = reshape(stiffness*odf',6,6)

C =

  183.5631   82.9671   88.5836    2.7986    1.1372   -0.9082
   82.9671  190.5425   84.1662   -2.5182   -1.4997   -0.5737
   88.5836   84.1662  181.5218   -2.0695    1.2460    0.8856
    2.7986   -2.5182   -2.0695   50.3526   -0.9322    1.1936
    1.1372   -1.4997    1.2460   -0.9322   46.9598   -2.6554
   -0.9082   -0.5737    0.8856    1.1936   -2.6554   51.7213


In [15]:
C11(p) = C(1,1)

Undefined function or variable 'p'.


In [3]:
odfDim = 50;
setFac = zeros(1,odfDim-1);

In [5]:
A = rand(2,2,2);

In [15]:
remainFac = 1:1:odfDim-1

remainFac =

  Columns 1 through 13

     1     2     3     4     5     6     7     8     9    10    11    12    13

  Columns 14 through 26

    14    15    16    17    18    19    20    21    22    23    24    25    26

  Columns 27 through 39

    27    28    29    30    31    32    33    34    35    36    37    38    39

  Columns 40 through 49

    40    41    42    43    44    45    46    47    48    49


In [16]:
randDraw = randint(0,length(remainFac),5)

ans =

  logical

   0


In [6]:
isempty(A)

ans =

  logical

   0


In [13]:
isempty([0,0,0])

ans =

  logical

   0


In [11]:
isempty(setFac)

ans =

  logical

   0


In [17]:
randsample(5,3)

ans =

     3
     5
     1


In [73]:
constraint = [ 0.03153236,  0.08391342,  0.02473832,  0.02473832,  0.02473832,
        0.02473832,  0.02473832,  0.02473832,  0.02473832,  0.02473832,
        0.02473832,  0.02473832,  0.02473832,  0.02473832,  0.01320576,
        0.01320576,  0.01320576,  0.01320576,  0.01320576,  0.01320576,
        0.01320576,  0.01320576,  0.01320576,  0.01320576,  0.01320576,
        0.01320576,  0.00985683,  0.00985683,  0.00985683,  0.00985683,
        0.00985683,  0.00985683,  0.01016979,  0.01016979,  0.01016979,
        0.01016979,  0.01016979,  0.01016979,  0.01016979,  0.01016979,
        0.01016979,  0.01016979,  0.01016979,  0.01016979,  0.01197505,
        0.01197505,  0.01197505,  0.01197505,  0.01197505,  0.01197505];

In [50]:

  sat = 0; count = 0;
  propFunc = @alpha_Ti;
  odfs = [];
  Data = [];
  notSat = [];

In [75]:
constraint = volumefraction;

In [79]:

  data_RandEvery5 = [];
  odfDim = 50;
  FACTOR = 5;
  remainFac = 1:1:odfDim-1;
  setFac = zeros(1,odfDim-1);
  thsd = 1;

  outerLp = 1;
  while isempty(remainFac) == 0

        if length(remainFac) < FACTOR
            println('thsd',thsd)
            r = 1;
        else
            println('thsd',thsd)
            r = FACTOR;
        end

        randDraw = randsample(length(remainFac),r);
        randFac = remainFac(randDraw); %This is the remaining fraction of the
        remainFac(randDraw) = [];

        randFacRand = rand(1,r).*thsd;

        innerLp(outerLp) = 1;

        while sum(randFacRand) > thsd
            randFacRand = rand(1,r).*thsd; %This is the
            innerLp(outerLp) = innerLp(outerLp) + 1;
        end

        thVector(outerLp) = thsd;

        thsd = thsd - sum(randFacRand); %thsd is the remainder after removing the

        setFac(randFac) = randFacRand./constraint(randFac);

        outerLp = outerLp + 1;
    end

      odf = [setFac,thsd/constraint(end)];
      if (odf>=0) == true(1,length(odf))
          [val,C11,C12] = propFunc(odf);
          println(odf);
          if val == -10000;
              count = count + 1;
              notSat = [notSat;odf,C11,C12,-val];
            else
    	        sat = sat + 1;
    	         disp(strcat('row',num2str(sat),'satisfied....'));
               println(C11,'      ',C12,'       ',val);
    	          odfs = [odfs;odf,-val];
                Data = [Data;odf,C11,C12,-val];
            end
        println('Sum is ', sum(odf.*volumefraction));
        end

thsd1
thsd0.13708
thsd0.0056361
thsd0.00046161
thsd2.4657e-06
thsd1.2773e-07
thsd1.401e-08
thsd3.1625e-09
thsd1.077e-09
thsd1.0603e-10
thsd1.7252e-11
thsd7.7417e-12
thsd3.5257e-12
10000
165.5304
73.3171

opt =

      -10000

3.24754     0.341713  1.70421e-10  9.50495e-09  1.12818e-07  7.88285e-09  4.03288e-09  2.33765e-05  3.78619e-08  3.58874e-09    0.0375258   0.00203289  1.15565e-05      1.89354     0.756061      19.8302  4.37747e-06     0.686173   8.5469e-05  3.03893e-08  8.24683e-09   0.00891119  9.12008e-08  4.15132e-08  2.32064e-09     0.360989    0.0607442      43.9101  2.86209e-06  4.89065e-06     0.184918  6.92876e-07  2.74252e-10  1.46733e-06   1.8161e-08    0.0104715    0.0116107     0.514281  6.00952e-08  2.91976e-05      9.11663     0.014733  9.35163e-10     0.168958  2.23687e-07  3.02703e-07   2.1148e-08  4.97131e-07   0.00194302  6.15165e-11
Sum is1


In [40]:
volumefraction

volumefraction =

  Columns 1 through 7

    0.0315    0.0839    0.0247    0.0247    0.0247    0.0247    0.0247

  Columns 8 through 14

    0.0247    0.0247    0.0247    0.0247    0.0247    0.0247    0.0247

  Columns 15 through 21

    0.0132    0.0132    0.0132    0.0132    0.0132    0.0132    0.0132

  Columns 22 through 28

    0.0132    0.0132    0.0132    0.0132    0.0132    0.0099    0.0099

  Columns 29 through 35

    0.0099    0.0099    0.0099    0.0099    0.0102    0.0102    0.0102

  Columns 36 through 42

    0.0102    0.0102    0.0102    0.0102    0.0102    0.0102    0.0102

  Columns 43 through 49

    0.0102    0.0102    0.0120    0.0120    0.0120    0.0120    0.0120

  Column 50

    0.0120


In [53]:
x = odf.*volumefraction;


In [82]:
counter = [];
odfs = [];
Data = [];
count = 0;  odfDim = 50;
randsize=1;num=2;
load alphatitaniumsmall;
constraint = volumefraction;
tic
% 1 partition - odfDim outcomes 50 for Titanium, 76 for Galfenol
if num == 1
	for i = 1:odfDimq
        odf_1 = zeros(1,odfDim);
        odf_1(i) = 1./constraint(i);
        odf = odf_1(i)
        [val,C11,C12] = alpha_Ti(odf_1);
        if val == -10000
            count = count + 1;
        else
        odfs = [odfs;odf_1,-val];
        Data = [Data;odf_1,val,C11,C12,-val];

        end
	end

else

	[odfarray,dataarray,invalid] = randSmallPartition(num,randsize,@alpha_Ti);
  println(length(odfarray)) ;
	odfs = [odfs;odfarray];
	Data = [Data;dataarray];
end
toc
t = toc;
t_Y_RkI = t;
println('Invalid',invalid);
println('Sum is ', sum(odf.*volumefraction));
println(t);

10000
243.7699
117.2746

opt =

      -10000

all invalid
0
Elapsed time is 0.006856 seconds.
Invalid1
Sum is1
0.0071848


In [15]:
A = 'C11';
A = 'alpha';

In [16]:
if strcmp(A,'alpha')
    println('alpha');
else
    println('C11')
end;

alpha


In [20]:
load linprog849_compliance_node
compliance = propmat(1:36,:);
volumefraction = propmat(end,:);

n = 388; %number of independent nodes
odf = zeros(n,1);

p = 2;
odf(p) = 1./volumefraction(1,p);
S = reshape(compliance*odf,6,6);
S11 = S(1,1);
S22 = S(2,2);
YieldStress = yield*odf

YieldStress =

  242.7970


In [7]:
size(propmat)

ans =

     1   388


In [10]:
a = [1 2 3 4 9 1 6 5 3 0]

a =

     1     2     3     4     9     1     6     5     3     0


In [25]:
size(propmat)

ans =

    37   388


In [26]:
size(compliance), size(volumefraction)

ans =

    36   388


ans =

     1   388


In [1]:
data = load('alphatitaniummedium.mat')



data = 

  struct with fields:

      volumefraction: [1�388 double]
           stiffness: [36�388 double]
    thermalexpansion: [9�388 double]



In [2]:
stiffness = data.stiffness;
volumefraction = data.volumefraction;

In [9]:
odfDat = load('testYieldUpper.mat');
Odf = odfDat.odf';


In [23]:
complianceFile = load('linprog849_compliance_node.mat');

In [24]:
vf = complianceFile.propmat(end,:);

In [25]:
size(Odf), size(stiffness),size(volumefraction),size(vf)


ans =

   388     1


ans =

    36   388


ans =

     1   388


ans =

     1   388



In [16]:
C= reshape(stiffness*Odf,6,6);


In [18]:
S11 = S(1,1);
S22 = S(2,2);

In [17]:
S = inv(C);

In [19]:
S11


S11 =

    0.0078



In [3]:
population = [385, 372, 315, 246, 374,  42, 313, 317, 196, 334, 337, 369, 371,384,   3, 257, 264, 266, 139, 142, 272, 147, 153, 324,  27, 157,32, 161, 163,  38, 295, 305, 310, 314, 194, 182, 225, 177, 332,339, 340, 214, 343,  91, 350, 351, 224, 367, 108, 365, 381, 368,125, 255]


population =

  Columns 1 through 13

   385   372   315   246   374    42   313   317   196   334   337   369   371

  Columns 14 through 26

   384     3   257   264   266   139   142   272   147   153   324    27   157

  Columns 27 through 39

    32   161   163    38   295   305   310   314   194   182   225   177   332

  Columns 40 through 52

   339   340   214   343    91   350   351   224   367   108   365   381   368

  Columns 53 through 54

   125   255



In [7]:
save('populationYield_nonLinear.mat','population')

In [9]:
odfDim = 388


odfDim =

   388

